version: '3.8'

services:
  weather:
    image: "${WEATHER_IMAGE}"
    container_name: weather
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres:5432
    healthcheck:
      test: "curl -f http://localhost:3000/health"
      interval: 60s
      start_period: 2s
  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 60s
      start_period: 2s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
